version: '3.4'

services:
  notejam:
    image: notejam
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      
  Nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
        - ./db/:/root/db/
    